meta_product_name: "Dressd"
meta_title: "Dressd - Wardrobe styler"
meta_description: "Your digital wardrobe. Upload your items and plan your outfits"
meta_image: "dressd-logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
